### ISSUE TITLE
ModuleNotFoundError: No module named 'dataLoader.nsvf'

### ISSUE THREAD

**Issue by Geniusyingmanji** [Shiran-Yuan/SlimmeRF#1]
Traceback (most recent call last):
  File "train.py", line 5, in <module>
    from renderer import *
  File "/data/zhouyf/SlimmeRF/renderer.py", line 3, in <module>
    from dataLoader.ray_utils import get_rays
  File "/data/zhouyf/SlimmeRF/dataLoader/__init__.py", line 3, in <module>
    from .nsvf import NSVF
ModuleNotFoundError: No module named 'dataLoader.nsvf'

**Comment by Shiran-Yuan** [comment]
Thanks for your interest. Seems that I missed some patches when refactoring the open-source code... oops ¯\_(ツ)_/¯

Please allow for a week or so. We're also adding some final touches to the camera-ready version of the paper, so updated versions of everything should be up and ready soon.

**Comment by Shiran-Yuan** [comment]
Oh, issue fixed a few days ago, I just remembered to close this lol
