### ISSUE TITLE
请问能在移动端设备进行渲染吗

### ISSUE THREAD

**Issue by Wangman1** [Shiran-Yuan/SlimmeRF#2]
您好，感谢您优秀的工作，请问能在移动端设备进行渲染吗

**Comment by Shiran-Yuan** [comment]
多谢关注。如果您说的是算力是否够的话我觉得训练好的模型slim完放到移动端应该是可以的。不过模型本身只能支持2D novel view synthesis和mesh生成之类的，所以如果您说的是类似于大部分移动端设备demo里的那种可交互建模的话肯定是不行的，inference speed跟不上。

**Comment by Shiran-Yuan** [comment]
我看到您在其他代码仓库也问了是否可以移动端渲染。具体deploy到移动端的方式的话个人推荐可以用网页试一试。

**Comment by Wangman1** [comment]
嘻嘻，感谢您的回复，最近刚开始看看端侧部署，发现很多都是借助webGL部署的，也就是您说的方案，可以一试，再次感谢您呀~~

**Comment by Shiran-Yuan** [comment]
不用谢，后面还有问题欢迎再开issue交流🤝
