### ISSUE TITLE
Assistance Request Regarding ImportError

### ISSUE THREAD

**Issue by wtj-zhong** [Shiran-Yuan/SlimmeRF#3]
I encountered the following ImportError while trying to run python train.py --config config/llff/fern.txt:

Traceback (most recent call last):
File "train.py", line 5, in <module>
from renderer import *
File "/home/alex/桌面/SlimmeRF/renderer.py", line 4, in <module>
from models.tensoRF import TensorVM, TensorCP, raw2alpha, TensorVMSplit, AlphaGridMask
ImportError: cannot import name 'TensorVM' from 'models.tensoRF' (/home/alex/桌面/SlimmeRF/models/tensoRF.py)

Is there any update or change related to 'TensorVM'? Could this issue be due to a misspelling of the module name or a path problem? I appreciate your guidance and advice.

Thank you for your assistance!

**Comment by Shiran-Yuan** [comment]
Thank you very much for the bug report. TensorVM is a class from TensoRF, and SlimmeRF does not use it, so I've probably uploaded the wrong version of renderer.py... I have deleted the import for this class. Many thanks again!

**Comment by Shiran-Yuan** [comment]
I'm closing this for now. If any further problems pop up feel free to reopen.
